receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  prometheusremotewrite:
    endpoint: "http://load-balancer:9009/api/v1/push"
    tls:
      insecure: true
    external_labels:
      job: "otel-collector"
    headers:
      X-Scope-OrgID: demo
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite, debug]